# Generated by Django 4.2.1 on 2023-05-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shift_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activity', models.CharField(max_length=20)),
                ('time_activity', models.IntegerField(default=0)),
            ],
        ),
    ]
